server {
  listen 80;
  server_name _;
  root /usr/share/nginx/html;
  index index.html;

  # API -> gateway-web (strip /api)
  location /api/ {
    proxy_pass http://gateway-web:8080/;
    proxy_set_header Host $host;
  }

  # MF proxiji (prefix ostane, upstream dobi cel URI)
  location /mf-studenti/ {
    proxy_pass http://mf-studenti;
    proxy_set_header Host $host;
  }

  location /mf-izpiti/ {
    proxy_pass http://mf-izpiti;
    proxy_set_header Host $host;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}