services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: studenti
      POSTGRES_USER: studenti
      POSTGRES_PASSWORD: studenti
    ports:
      - "5433:5432"
    volumes:
      - studenti_db:/var/lib/postgresql/data

  studenti-api:
    build: .
    environment:
      DATABASE_URL: postgresql+psycopg2://studenti:studenti@db:5432/studenti
      LOG_LEVEL: INFO
    depends_on:
      - db
    ports:
      - "8001:8000"

volumes:
  studenti_db: