apiVersion: v1
kind: Secret
metadata:
  name: db-secrets
type: Opaque
stringData:
  STUDENTI_DB_USER: studenti
  STUDENTI_DB_PASS: studenti
  IZPITI_DB_USER: izpiti
  IZPITI_DB_PASS: izpiti

  MONGO_ROOT_USER: root
  MONGO_ROOT_PASS: root

  ARTEMIS_USER: admin
  ARTEMIS_PASS: admin
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
data:
  DOGODKI_QUEUE: events.v1
